quotesURL='https://api.tdameritrade.com/v1/marketdata/quotes'
marketsURL='https://api.tdameritrade.com/v1/marketdata/hours'
moversURL='https://api.tdameritrade.com/v1/marketdata/{index}/movers'
quotesURL='https://api.tdameritrade.com/v1/marketdata/quotes'
priceHistoryURL='https://api.tdameritrade.com/v1/marketdata/{index}/pricehistory'
fundDataURL='https://api.tdameritrade.com/v1/instruments'